spring:
  data:
    mongodb:
      uri: ${URI_MONGODB}
      auto-index-creation: true


server:
  port: 8080
  
  servlet:
    context-path: /api/v1
    
  error:
    include-stacktrace: never

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true


springdoc:
  packagesToScan: com.vuex.example.vuex.controller
 
  api-docs:
    enabled: true
  
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html